[project]
name = "dbclust"
version = "0.2"
description = ""
authors = [
    { name = "Marc Grunberg", email = "marc.grunberg@unistra.fr" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alphabetic_timestamp",
    "dacite",
    "dateparser",
    "duckdb",
    "fastapi",
    "fastparquet",
    "geopandas",
    "hdbscan",
    "icecream",
    "jinja2",
    "numpy",
    "obspy",
    "pandas",
    "plotly",
    "plotext",
    "prettytable",
    "pyocto>=0.1.8",
    "pyproj",
    "ray",
    "rich",
    "scikit-learn",
    "scipy",
    "starlette",
    "tqdm",
    "uvicorn",
    "spatialite>=0.0.3",
    "psutil>=7.0.0",
    "pre-commit>=4.2.0",
    "pyrocko>=2025.1.10",
    "visidata>=3.1.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["dbclust", "fdsnws"]

[project.scripts]
fdsnws-server = "fdsnws.server:main"
dbclust = "dbclust.runner:main"
injectdb = "dbclust.inject_spatialite:main"

[project.urls]
"Homepage" = "https://github.com/marcopovitch/dbclust"
"Bug Tracker" = "https://github.com/marcopovitch/dbclust/issues"
