file:
  # root Data path
  data_path: &DATA /datadir

  #temporary directory
  tmp_path: "/tmp/nll"
  obs_path: "/tmp/obs"

pick:
  # path to phaseNet/EQT picks file
  path: !join &PICK_PATH [*DATA, "/", "picks"]
  filename: !join [ *PICK_PATH, "/", "picks.csv", ]
  type: phasenetsds

  # force pick uncertainty
  P_uncertainty: 0.1
  S_uncertainty: 0.2

  # import only phase with proba >= phase_proba_threshold
  P_proba_threshold: 0.3
  S_proba_threshold: 0.3

  # use only picks in this time window
  # filter picks between [date_begin, date_end]
  start: 2022-01-01T00:00:00.000Z
  end:   2023-01-01T00:00:00.000Z

station:
  # must be [inventory, fdsnws]
  fetch_method: fdsnws
  # inventory is a list of file to import
  inventory_files:
  # base url for fdsnws station
  fdsnws_url: http://10.0.1.36:8080

  # Remove all picks containing theses regex
  blacklist:
  #  - ^FR.*
  #  - ^FO.*
  #  - ^RA.*

time:
  # work on max time_window (mind the units !)
  # computation time increase a lot with time_window
  time_window: 15 # minutes
  # time window for data overlapping (mind the units !)
  overlap_window: 30 # seconds

# parameters for clustering
cluster:
  # used by hdbscan
  min_cluster_size: &MIN_CLUSTER_SISE 3

  # discard cluster with stations count (without duplicate) below this value
  min_station_count: &CLUSTER_MIN_STATION_COUNT 5
  # discard cluster and origin without enough stations having both P and S phases
  min_station_with_P_and_S: 2

  # km/s
  average_velocity: 5
  # no more useful with hdbscan
  # but can be forced (called epsilon or eps)
  max_search_dist: 8.0
  # nb of picks in common to merge cluster in the overlapped zone
  min_picks_common: 3

  # WARNING : to be used only for a unique event !
  # Don't use it if you don't know what you are doing !
  # pre_computed_tt_matrix_file: !join [*DATA, "/", "tt_matrix-min_size", *MIN_CLUSTER_SISE, ".npy"]

nll:
  # NLLoc binary
  nlloc_bin: /opt/nll/bin/NLLoc

  scat2latlon_bin: /opt/nll/bin/scat2latlon

  # time grid files
  time_path: /nll/times

  # location of nll configuration template directory
  template_path: /nll/nll_template

  # use this profile by default
  default_velocity_profile: haslach-0.2
  velocity_profiles:
    - name: alpes
      template: nll_alpes_template.conf

    - name: auvergne
      template: nll_auvergne_template.conf

    - name: haslach-0.2
      template: nll_haslach-0.2_template.conf

    - name: pyrenees
      template: nll_pyrenees_template.conf

    - name: rittershoffen
      template: nll_rittershoffen_template.conf

    - name: vendenheim
      template: nll_vendenheim_template.conf

  # file to keep track of SCNL when importing NLL obs file
  # file format: NET_STA_LOC_CHAN
  #   eg. FR_PYHE_00_HHZ
  # channel_hint: null
  channel_hint: !join [*DATA, "/", "chan.txt"]

  # verbose
  verbose: False

  # produce scatter file
  enable_scatter: False

# enable a nll relocation (ie. double pass) with pick filtering
# based on pick's time residual threshold
relocation:
  # station cutoff distance
  # set null to ignore the cutoff
  dist_km_cutoff: null
  double_pass: True
  P_time_residual_threshold: 0.50
  S_time_residual_threshold: 1.00
  # P_time_residual_threshold: 1.0
  # S_time_residual_threshold: 1.5

# force these attributes in quakeml file
quakeml:
  event_prefix: eost
  smi_base: smi:franceseisme.fr
  agency_id: RENASS
  author: DBClust
  evaluation_mode: automatic
  #evaluation_mode: manual
  method_id: NonLinLoc
  #model_id: will be set to the profile name used

# Catalog will be saved more or less every event_flush_count
# resulting file will be : "qml_base_filename-part-%d.qml"
catalog:
  # path definition to store catalog files
  path: !join &QML_PATH [*DATA, "/", "qml"]
  qml_base_filename: selestat
  event_flush_count: 100

pyocto:
  default_model_name: haslach
  # directory to store velocity model
  path: !join [*DATA, "/", "vmodels"]
  models:
    - name: haslach
      associator:
        time_before: 0 # overlap window
        max_pick_overlap: 0 # as there is no overlap window
        min_pick_fraction: 0.35
        zlim: [0, 40]
        min_node_size: 5
        min_node_size_location: 1.5
        pick_match_tolerance: 5
        n_picks: 5
        n_p_picks: 3
        n_s_picks: 2
        # n_p_and_s_picks doesn't seem to work !
        # set it to 0 and rely on dbclust's min_station_with_P_and_S
        # to accept/reject origin.
        # n_p_and_s_picks: *MIN_P_AND_S
        n_p_and_s_picks: 0

      velocity_model:
        depth: [0.0, 2.4, 20.1, 30.2]
        vp: [5.63, 5.97, 6.54, 8.15]
        vs: [3.41, 3.45, 3.65, 4.4]
        tolerance: 2.0
        grid_spacing_km: 1
        max_horizontal_dist_km: 1500
        max_vertical_dist_km: 35

# Warning: [longitude, latitude]
# Order is important as first match is returned.
# World at the end is the default model.
# velocity_profile is the nll velocity name to be used.
zones:
  zones:
    - name: alpes
      velocity_profile: alpes
      polygone:
        [[4.84, 47.0], [8.50, 47.0], [8.50, 43.8], [5.88, 42.9], [4.50, 43.8]]
    - name: grand-est
      velocity_profile: haslach-0.2
      polygone: [[4.84, 47.0], [-6.20, 49.8], [8.70, 49.0], [8.50, 47.0]]
    - name: massif-central
      velocity_profile: auvergne
      polygone:
        [
          [4.84, 47.0],
          [2.3964, 47.0844],
          [0.34, 46.5800],
          [0.34, 43.68],
          [3.5, 43.1],
          [4.5, 43.8],
        ]
    - name: mediterranee
      velocity_profile: haslach-0.2
      polygone:
        [
          [10, 41.0],
          [3.5, 41.9],
          [3.5, 43.1],
          [4.5, 43.8],
          [5.88, 42.9],
          [8.50, 43.8],
          [10.0, 43.8],
        ]
    - name: nord
      velocity_profile: haslach-0.2
      polygone:
        [
          [2.3964, 47.0844],
          [0.000, 50.000],
          [2.00, 51.8],
          [6.2, 49.8],
          [4.84, 47.0],
        ]
    - name: pyrenees
      velocity_profile: pyrenees
      polygone:
        [
          [-2.3, 43.5],
          [-1.2, 43.8],
          [0.34, 43.68],
          [3.5, 43.1],
          [3.5, 41.9],
          [3.0, 41.5],
          [-2.1, 42.3],
        ]
    - name: ouest
      velocity_profile: haslach-0.2
      polygone:
        [
          [2.3964, 47.0844],
          [-0.5000, 50.5000],
          [-5.000, 50.000],
          [-5.8, 48.2],
          [-5.7, 44.5],
          [-2.3, 43.5],
          [-1.2, 43.8],
          [0.34, 43.68],
          [0.34, 46.58],
        ]
    - name: world
      velocity_profile: haslach-0.2
      polygone: [[-180, 90], [180, 90], [180, -90], [-180, -90]]
